=== PawanShreSth/XML-CSS-Project/catalog_19031260.dtd
<!ELEMENT store (store_info, songs)>
<!ELEMENT store_info (logo,store_name,about?,country,city,address,contact_info,website?)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT store_name (#PCDATA)>
<!ELEMENT about (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT contact_info (email_id,phone_num)>
<!ATTLIST contact_info contact_id CDATA #REQUIRED>
<!ELEMENT email_id (#PCDATA)>
<!ELEMENT phone_num (#PCDATA)>

<!ELEMENT website (#PCDATA)>

<!ELEMENT songs (song+)>
<!ELEMENT song (song_name,genre,song_info?,song_writer,singers_list,song_length?,album,producers_name*,director_name*,release_date,language,rating,cost,stock)>
<!ATTLIST song song_id CDATA #REQUIRED>
<!ELEMENT song_name (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT song_info (#PCDATA)>
<!ELEMENT song_writer (#PCDATA)>

<!ELEMENT singers_list (singer_name,singer_nationality?)>
<!ATTLIST singers_list list CDATA #REQUIRED>
<!ELEMENT singer_name (#PCDATA)>
<!ELEMENT singer_nationality (#PCDATA)>

<!ELEMENT song_length (#PCDATA)>
<!ELEMENT album (#PCDATA)>

<!ELEMENT producers_name (full_name,nationality?)>
<!ATTLIST producers_name producer_list CDATA #REQUIRED>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>

<!ELEMENT director_name (#PCDATA)>
<!ATTLIST director_name director_id CDATA #REQUIRED>

<!ELEMENT release_date (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT cost (Nepali,Dollar)>
<!ELEMENT Nepali (#PCDATA)>
<!ELEMENT Dollar (#PCDATA)>

<!ELEMENT stock (#PCDATA)>

=== PawanShreSth/XML-CSS-Project/catalog_19031260.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD -->
<!-- <!DOCTYPE store SYSTEM "catalog_19031260.dtd"> -->

<!-- CSS -->
<?xml-stylesheet type="text/css" href="./catalog_19031260.css" ?>

<!-- Schema -->
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="catalog_19031260.xsd">
		<store_info>
			<logo></logo>
			<store_name>Soul Sound</store_name>			
			<about>Soul Sound is the leading comany of Nepal to provide the record 
			of different genre ranging from folk, Blues, Jazz, Pop, Hip Hop, Rock, 
			Opera, Country and many more. We are aware that music has no border so 
			we sell English, Spanish, Nepalese, Hindi and popular music from all 
			around the world. If anyone wants to buy a music, we are here to serve in 
			all the major cities in Nepal.</about>
			<country>Nepal</country>
			<city>Kathmandu</city>
			<address>Kalanki</address>
			<contact_info contact_id="1">
				<email_id>soulsound@gmail.com</email_id>
				<phone_num>977-98413242331</phone_num>
			</contact_info>
			<website>www.soulsound.com</website>
		</store_info>
		

		<songs>
			<song song_id="01">
				<song_name>Dirty Deeds Done Dirt Cheap</song_name>
				<genre>Rock</genre>
				<song_info>Dirty Deeds Done Dirt Cheap is the third studio album by Australian hard rock band AC/DC. It was the band's third LP released in Australia and second in Europe in 1976 but was not released in the United States until 1981, more than one year after lead singer Bon Scott's death.</song_info>
				<song_writer>Angus Young, Bon Scott &amp; Malcolm Young</song_writer>				
				<singers_list list="1">
					<singer_name>AC/DC</singer_name>
					<singer_nationality>USA </singer_nationality>					
				</singers_list>
				<song_length>4:11</song_length>
				<album>Dirty Deeds Done Dirt Cheap</album>
				<producers_name producer_list="S1">
					<full_name>Harry Vanda, George Young</full_name>
					<nationality>USA</nationality>
				</producers_name>
				<director_name director_id="1">Mark Evans</director_name>
				<release_date>1976</release_date>
				<language>English</language>
				<rating>9.5</rating>
				<cost>
					<Nepali>500</Nepali>
					<Dollar>5</Dollar>
				</cost>
				<stock>Available</stock>
			</song>


			<song song_id="02">
				<song_name>Blank Space</song_name>
				<genre>Electropop</genre>
				<song_info>Blank Space is a song by American singer-songwriter Taylor Swift, taken from her fifth studio album, 1989.</song_info>
				<song_writer>Taylor Swift</song_writer>				
				<singers_list list="1">
					<singer_name>Taylor Swift</singer_name>
					<singer_nationality>USA </singer_nationality>					
				</singers_list>
				<song_length>3:52</song_length>
				<album>1989</album>
				<producers_name producer_list="S1">
					<full_name>Max Martin &amp; Shellback</full_name>
					<nationality>USA</nationality>
				</producers_name>
				<director_name director_id="2">Joseph Kahn</director_name>
				<release_date>2014</release_date>
				<language>English</language>
				<rating>9.0</rating>
				<cost>
					<Nepali>500</Nepali>
					<Dollar>5</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="03">
				<song_name>Love Story</song_name>
				<genre>Country pop</genre>
				<song_info>&quot;Love Story&quot; is a song written and recorded by American singer-songwriter Taylor Swift. It was released on September 12, 2008 by Big Machine Records, as the lead single from Swift's second studio album Fearless (2008), co-produced by Nathan Chapman.</song_info>
				<song_writer>Taylor Swift</song_writer>				
				<singers_list list="1">
					<singer_name>Taylor Swift</singer_name>
					<singer_nationality>USA </singer_nationality>					
				</singers_list>
				<song_length>3:57</song_length>
				<album>Taylor Swift Tribute Album: Greatest Hits Streamed</album>
				<producers_name producer_list="S1">
					<full_name>Nathan Chapman</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="3">Trey Fanjoy</director_name>
				<release_date>2015</release_date>
				<language>English</language>
				<rating>9.5</rating>
				<cost>
					<Nepali>600</Nepali>
					<Dollar>6</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="04">
				<song_name>Psychosocial</song_name>
				<genre>Alternative metal</genre>
				<song_info>Psychosocial is a song by American heavy metal band Slipknot. It was released as the second single and fourth track from their fourth studio album, All Hope Is Gone.</song_info>
				<song_writer>Corey Taylor, Joey Jordison, Paul Gray</song_writer>				
				<singers_list list="1">
					<singer_name>Corey Taylor</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>3:57</song_length>
				<album>All Hope Is Gone</album>
				<producers_name producer_list="S1">
					<full_name>Dave Fortman</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="4">Paul Brown</director_name>
				<release_date>2008</release_date>
				<language>English</language>
				<rating>8</rating>
				<cost>
					<Nepali>700</Nepali>
					<Dollar>7</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="05">
				<song_name>Before I Forget</song_name>
				<genre>Metal</genre>
				<song_info>Before I Forget is a Grammy Award-winning song by American heavy metal band Slipknot.</song_info>
				<song_writer>Shawn Crahan, Chris Fehn, Paul Gray, Craig Jones, Joey Jordison, Jim Root, Corey Taylor, Mick Thomson, Sid Wilson</song_writer>				
				<singers_list list="1">
					<singer_name>Corey Taylor</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>4:38</song_length>
				<album>Vol. 3: The Subliminal Verses</album>
				<producers_name producer_list="S1">
					<full_name>Rick Rubin</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="5">Tony Petrossian</director_name>
				<release_date>2005</release_date>
				<language>English</language>
				<rating>9</rating>
				<cost>
					<Nepali>700</Nepali>
					<Dollar>7</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="06">
				<song_name>Dead Memories</song_name>
				<genre>Alternative Metal</genre>
				<song_info>Dead Memories is a song from American heavy metal band Slipknot's fourth album, All Hope Is Gone</song_info>
				<song_writer>Corey Taylor</song_writer>				
				<singers_list list="1">
					<singer_name>Corey Taylor</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>4:29</song_length>
				<album>All Hope Is Gone</album>
				<producers_name producer_list="S1">
					<full_name>Dave Fortman</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="6">P.R. Brown, Shawn Crahan</director_name>
				<release_date>2008</release_date>
				<language>English</language>
				<rating>7</rating>
				<cost>
					<Nepali>500</Nepali>
					<Dollar>5</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="07">
				<song_name>Walk with Me in Hell</song_name>
				<genre>Groove Metal</genre>
				<song_info>Walk with Me in Hell is a 2008 live DVD by American metal band Lamb of God. </song_info>
				<song_writer>Lamb of God</song_writer>				
				<singers_list list="1">
					<singer_name>Randy Blythe</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>4:29</song_length>
				<album>As in the places Burn</album>
				<producers_name producer_list="S1">
					<full_name>Space Monkey Studios, Inc.</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="7">Doug Spangenberg</director_name>
				<release_date>2008</release_date>
				<language>English</language>
				<rating>7.5</rating>
				<cost>
					<Nepali>500</Nepali>
					<Dollar>5</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="08">
				<song_name>Boulevard of Broken Dreams</song_name>
				<genre>Alternative Rock</genre>
				<song_info>Boulevard of Broken Dreams is a song by American rock band Green Day. It is the fourth track from their seventh studio album American Idiot (2004).</song_info>
				<song_writer>Billie Joe Armstrong, Mike Dirnt, Tre Cool</song_writer>				
				<singers_list list="1">
					<singer_name>Billie Joe Armstrong</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>4:20</song_length>
				<album>Holiday</album>
				<producers_name producer_list="S1">
					<full_name>Rob Cavallo</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="8">Samuel Bayer</director_name>
				<release_date>2004</release_date>
				<language>English</language>
				<rating>7.5</rating>
				<cost>
					<Nepali>600</Nepali>
					<Dollar>6</Dollar>
				</cost>
				<stock>Available</stock>
			</song>

			<song song_id="09">
				<song_name>21 Guns</song_name>
				<genre>Alternative Rock</genre>
				<song_info>21 Guns is a song by American rock band Green Day. It was released as the second single from their eighth album, 21st Century Breakdown.</song_info>
				<song_writer>Billie Joe Armstrong, Mike Dirnt, Tre Cool</song_writer>				
				<singers_list list="1">
					<singer_name>Billie Joe Armstrong</singer_name>
					<singer_nationality>USA</singer_nationality>					
				</singers_list>
				<song_length>5:21</song_length>
				<album>21st Century Breakdown</album>
				<producers_name producer_list="S1">
					<full_name>Butch Vig</full_name>
					<nationality>USA</nationality>
				</producers_name>

				<director_name director_id="9">Marc Webb</director_name>
				<release_date>2008</release_date>
				<language>English</language>
				<rating>7</rating>
				<cost>
					<Nepali>600</Nepali>
					<Dollar>6</Dollar>
